spring:
  datasource:
    url : jdbc:mysql://192.168.37.20:3306/hn_app?autoReconnect=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&characterEncoding=utf8&serverTimezone=UTC
    username : admin
    password : Gobest123$%^
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
      mode: LEGACYHTML5
      encoding: UTF-8
      cache: false
      check-template-location: true
      enabled: true
      prefix: classpath:/templates/
